# Generated by Django 4.2.5 on 2023-10-24 09:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicensePlates',
            fields=[
                ('license_platesID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('license_plates', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingHistory',
            fields=[
                ('parking_historyID', models.CharField(default='', max_length=15, primary_key=True, serialize=False)),
                ('state', models.IntegerField()),
                ('date_in', models.DateField(default=django.utils.timezone.now)),
                ('date_out', models.DateField(default=django.utils.timezone.now)),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('total', models.FloatField()),
                ('note', models.TextField(null=True)),
                ('license_plates', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.licenseplates')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(default='user00002958', max_length=15, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=255)),
                ('state', models.IntegerField()),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('photo', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default='user00007433', max_length=15, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('fullname', models.CharField(max_length=50, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('position', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('account_balance', models.FloatField(default=0.0)),
                ('photo', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffParking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffID', models.CharField(max_length=15)),
                ('parking_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.parkinghistory')),
            ],
        ),
        migrations.CreateModel(
            name='LicensePlatesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=15)),
                ('license_plates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.licenseplates')),
            ],
        ),
        migrations.CreateModel(
            name='LicensePlatesParking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_historyID', models.CharField(max_length=15)),
                ('license_plates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.licenseplates')),
            ],
        ),
    ]
