# Generated by Django 4.2.5 on 2023-10-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_role_alter_staff_staff_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinghistory',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='parkinghistory',
            name='parking_historyID',
            field=models.CharField(default='park00108882', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(default='user00049356', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='user00135626', max_length=15, primary_key=True, serialize=False),
        ),
    ]
