# Generated by Django 4.2.5 on 2023-11-06 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_parkinghistory_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinghistory',
            name='date_out',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkinghistory',
            name='parking_historyID',
            field=models.CharField(default='park00175396', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parkinghistory',
            name='time_in',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='parkinghistory',
            name='time_out',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='parkinghistory',
            name='total',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(default='user00807969', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='user00163785', max_length=15, primary_key=True, serialize=False),
        ),
    ]
